Repository frgfm/sdcnd-capstone, pull requests merged in 2020-04, with the labels that each got.

#2 style: Added lint verification
  .flake8
  .github/workflows/main.yml
  ros/src/camera_info_publisher/yaml_to_camera_info_publisher.py
  ros/src/styx/bridge.py
  ros/src/styx/conf.py
  ros/src/styx/server.py
  ros/src/tl_detector/light_classification/tl_classifier.py
  ros/src/tl_detector/light_publisher.py
  ros/src/tl_detector/tl_detector.py
  ros/src/twist_controller/dbw_node.py
  ros/src/twist_controller/dbw_test.py
  ros/src/twist_controller/lowpass.py
  ros/src/twist_controller/pid.py
  ros/src/twist_controller/twist_controller.py
  ros/src/twist_controller/yaw_controller.py
  ros/src/waypoint_loader/waypoint_loader.py
  ros/src/waypoint_updater/waypoint_updater.py
Labels: module: control, module: perception, module: planning

#3 fix: Fixed original repo dependencies
  .gitignore
  Dockerfile
  ros/src/tl_detector/tl_detector.py
  ros/src/twist_controller/dbw_node.py
  ros/src/twist_controller/lowpass.py
  ros/src/twist_controller/twist_controller.py
  ros/src/waypoint_updater/waypoint_updater.py
Labels: topic: build

#4 fix: Fixed libwaypoint_follower deps
  .gitignore
  ros/src/waypoint_follower/lib/libwaypoint_follower.cpp
Labels: module: planning, topic: build

#5 chore: Added a docker build workflow
  .github/workflows/main.yml
  ros/src/dbw_mkz_msgs/CHANGELOG.rst
  ros/src/dbw_mkz_msgs/CMakeLists.txt
  ros/src/dbw_mkz_msgs/bmr/1.0.11-1.0.12/BrakeReport.bmr
  ros/src/dbw_mkz_msgs/bmr/1.0.11-1.0.12/BrakeReport.saved
  ros/src/dbw_mkz_msgs/bmr/1.0.11-1.0.12/SteeringReport.bmr
  ros/src/dbw_mkz_msgs/bmr/1.0.11-1.0.12/SteeringReport.saved
  ros/src/dbw_mkz_msgs/bmr/1.0.11-1.0.12/ThrottleReport.bmr
  ros/src/dbw_mkz_msgs/bmr/1.0.11-1.0.12/ThrottleReport.saved
  ros/src/dbw_mkz_msgs/bmr/1.0.12-1.0.13/Misc1Report.bmr
  ros/src/dbw_mkz_msgs/bmr/1.0.12-1.0.13/Misc1Report.saved
  ros/src/dbw_mkz_msgs/bmr/1.0.2-1.0.3/SteeringCmd.bmr
  ros/src/dbw_mkz_msgs/bmr/1.0.2-1.0.3/SteeringCmd.saved
  ros/src/dbw_mkz_msgs/bmr/1.0.5-1.0.6/BrakeCmd.bmr
  ros/src/dbw_mkz_msgs/bmr/1.0.5-1.0.6/BrakeCmd.saved
  ros/src/dbw_mkz_msgs/bmr/1.0.5-1.0.6/GearCmd.bmr
  ros/src/dbw_mkz_msgs/bmr/1.0.5-1.0.6/GearCmd.saved
  ros/src/dbw_mkz_msgs/bmr/1.0.5-1.0.6/SteeringCmd.bmr
  ros/src/dbw_mkz_msgs/bmr/1.0.5-1.0.6/SteeringCmd.saved
  ros/src/dbw_mkz_msgs/bmr/1.0.5-1.0.6/ThrottleCmd.bmr
  ros/src/dbw_mkz_msgs/bmr/1.0.5-1.0.6/ThrottleCmd.saved
  ros/src/dbw_mkz_msgs/bmr/1.0.6-1.0.7/BrakeReport.bmr
  ros/src/dbw_mkz_msgs/bmr/1.0.6-1.0.7/BrakeReport.saved
  ros/src/dbw_mkz_msgs/bmr/1.0.6-1.0.7/GearReport.bmr
  ros/src/dbw_mkz_msgs/bmr/1.0.6-1.0.7/GearReport.saved
  ros/src/dbw_mkz_msgs/bmr/1.0.6-1.0.7/Misc1Report.bmr
  ros/src/dbw_mkz_msgs/bmr/1.0.6-1.0.7/Misc1Report.saved
  ros/src/dbw_mkz_msgs/bmr/1.0.6-1.0.7/SteeringReport.bmr
  ros/src/dbw_mkz_msgs/bmr/1.0.6-1.0.7/SteeringReport.saved
  ros/src/dbw_mkz_msgs/bmr/1.0.6-1.0.7/ThrottleReport.bmr
  ros/src/dbw_mkz_msgs/bmr/1.0.6-1.0.7/ThrottleReport.saved
  ros/src/dbw_mkz_msgs/bmr/README.md
  ros/src/dbw_mkz_msgs/msg/AmbientLight.msg
  ros/src/dbw_mkz_msgs/msg/BrakeCmd.msg
  ros/src/dbw_mkz_msgs/msg/BrakeInfoReport.msg
  ros/src/dbw_mkz_msgs/msg/BrakeReport.msg
  ros/src/dbw_mkz_msgs/msg/FuelLevelReport.msg
  ros/src/dbw_mkz_msgs/msg/Gear.msg
  ros/src/dbw_mkz_msgs/msg/GearCmd.msg
  ros/src/dbw_mkz_msgs/msg/GearReject.msg
  ros/src/dbw_mkz_msgs/msg/GearReport.msg
  ros/src/dbw_mkz_msgs/msg/HillStartAssist.msg
  ros/src/dbw_mkz_msgs/msg/Misc1Report.msg
  ros/src/dbw_mkz_msgs/msg/ParkingBrake.msg
  ros/src/dbw_mkz_msgs/msg/SteeringCmd.msg
  ros/src/dbw_mkz_msgs/msg/SteeringReport.msg
  ros/src/dbw_mkz_msgs/msg/SurroundReport.msg
  ros/src/dbw_mkz_msgs/msg/ThrottleCmd.msg
  ros/src/dbw_mkz_msgs/msg/ThrottleInfoReport.msg
  ros/src/dbw_mkz_msgs/msg/ThrottleReport.msg
  ros/src/dbw_mkz_msgs/msg/TirePressureReport.msg
  ros/src/dbw_mkz_msgs/msg/TurnSignal.msg
  ros/src/dbw_mkz_msgs/msg/TurnSignalCmd.msg
  ros/src/dbw_mkz_msgs/msg/TwistCmd.msg
  ros/src/dbw_mkz_msgs/msg/WatchdogCounter.msg
  ros/src/dbw_mkz_msgs/msg/WheelPositionReport.msg
  ros/src/dbw_mkz_msgs/msg/WheelSpeedReport.msg
  ros/src/dbw_mkz_msgs/msg/Wiper.msg
  ros/src/dbw_mkz_msgs/package.xml
Labels: topic: build

#6 Raise brake intensity and Max throttle value
  ros/src/twist_controller/twist_controller.py
Labels: module: control

#7 feat: Added basic traffic light classifier node
  Dockerfile
  ros/src/tl_detector/light_classification/tl_classifier.py
  ros/src/tl_detector/tl_detector.py
  ros/src/twist_controller/dbw_node.py
  ros/src/twist_controller/twist_controller.py
  ros/src/waypoint_updater/waypoint_updater.py
Labels: documentation, module: perception, module: planning, topic: build

#8 style: Fixed method name of LP Filter
  ros/src/twist_controller/lowpass.py
  ros/src/twist_controller/twist_controller.py
Labels: enhancement, module: control

#9 feat: Adds a working traffic light detection module
  ros/src/tl_detector/light_classification/tl_classifier.py
  ros/src/tl_detector/tl_detector.py
  ros/src/waypoint_updater/waypoint_updater.py
Labels: module: perception, module: planning

#10 docs: Updated readme
  README.md
  static/images/capstone_green.png
  static/images/capstone_red.png
  static/images/capstone_result.gif
  static/images/capstone_start.png
Labels: documentation

#11 feat: Added model download when ROS master starts
  .gitignore
  ros/src/tl_detector/light_classification/tl_classifier.py
Labels: module: perception
